version: 2

builds:
  - id: go_api
    main: ./cmd/api/api.go
    binary: go_api
    env:
      - GOGC=150
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    flags:
      - -tags=!netpoll

archives:
  - id: go_api
    name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    formats: ['tar.gz']
    format_overrides:
      - goos: windows
        formats: ['zip']

checksum:
  name_template: 'checksum.txt'

snapshot:
  version_template: "{{ .Tag }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs\('
      - '^test\('
      - '^ci\('
      - '^build\('
      - '^style\('
      - '^refactor\('

release:
  github:
    owner: 'dbunt1tled'
    name: 'go-api'
  draft: false
  prerelease: auto

before:
  hooks:
    - go mod tidy
    - go generate ./...
