
required = "{{.Field}} обязательное поле."
lte = "{{.Field}} должно быть меньше {{.Tag}}"
gte = "{{.Field}} должно быть больше {{.Tag}}"
email = "{{.Field}} не является действительным email адресом."
url = "{{.Field}} не является действительным url."
oneof = "{{.Field}} должен быть одним из {{.Tag}}"
default_validation_message = "{{.Field}} не соответствует правилу {{.Tag}}"
unique_db = "{{.Field}} уже существует"

Login = "Логин"
FirstName = "Имя"
SecondName = "Фамилия"
Email = "Емейл"
PhoneNumber = "Телефон"
Status = "Статус"
Password = "Пароль"
Url = "Урл"
Alias = "Алиас"
CreatedAt = "Дата Создания"
UpdatedAt = "Дата Обновления"
Username = "Юзернейм"
Age = "Возраст"
Gender = "Пол"
Token = "Токен"
