required = "{{.Field}} is a required field."
lte = "{{.Field}} should be lower than {{.Tag}}"
gte = "{{.Field}} should be greater than {{.Tag}}"
email = "{{.Field}} is not a valid email address."
url = "{{.Field}} is not a valid url."
oneof = "{{.Field}} should be one of the {{.Tag}}"
default_validation_message = "{{.Field}} is not valid for rule {{.Tag}}"

Login = "Login"
FirstName = "First Name"
SecondName = "Second Name"
Email = "Email"
PhoneNumber = "Phone Number"
Status = "Status"
Password = "Password"
Url = "Url"
Alias = "Alias"
Id = "Id"
CreatedAt = "Created At"
UpdatedAt = "Updated At"
Username = "Username"
Age = "Age"
Gender = "Gender"